
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://github.com/MehVahdJukaar/WoodGood/issues" #optional

[[mods]] #mandatory

modId="everycomp" #mandatory

version = "${version}"

displayName="Every Compat" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/every-compat" #optional

logoFile="logo.png" #optional

credits="Plantkillable, WenXin2, Frogbirdd, Pau_1eal" #optional

authors="MehVahdJukaar" #optional

description='''Ultimate Wood Compat Mod'''

itemIcon="everycomp:all_woods" #catalogue icon


[[dependencies.everycomp]] #optional

modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[41.0.100,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.everycomp]]

modId="minecraft"
mandatory=true
versionRange="[1.20,1.21]"
ordering="NONE"
side="BOTH"

[[dependencies.everycomp]]

modId="moonlight"
mandatory=true
versionRange="[1.20-2.8.0,]"
ordering="NONE"
side="BOTH"

# ----------------------------------------------------- MODS -----------------------------------------------------------

[[dependencies.everycomp]] #optional

modId="mcwbridges"
mandatory=false
versionRange="[3.0.0,)" #mandatory
ordering="AFTER"
side="BOTH"

[[dependencies.everycomp]] #optional

modId="mcwfences"
mandatory=false
versionRange="[1.1.1,)" #mandatory
ordering="AFTER"
side="BOTH"




